### ISSUE TITLE
pulp module missing solvers

### ISSUE THREAD

**Issue by finsnoop** [leliel12/scikit-criteria#13]
Tried installing scikit-criteria on Debian 10 using pip install scikit-criteria and everything works just perfect until I try to import SIMUS class using from skcriteria.madm.simus import SIMUS

I get an attribution error: `AttributeError: module 'pulp' has no attribute 'solvers'`
I am running Python 3.8 and I have tried.

The developers of pulp noticed the problem and advised as follows: See `https://github.com/coin-or/pulp/issues/286`

1. They use a correct but not standard reference (pulp.solvers.SOME_SOLVER) when it should have been pulp.SOME_SOLVER.
2. We have now changed the files format, so the absolute reference should be pulp.apis.SOME_SOLVE. Nevertheless, pulp.SOME_SOLVER still works and should be encouraged.

As a fix, you could try opening an issue in their github so they take out the "solvers" part and leave it with pulp.SOME_SOLVER.

Could you please fix this?

**Comment by elcolie** [comment]
I also have this bug.
scikit-criteria==0.2.10

**Comment by leliel12** [comment]
Wow, I miss sorry. This is one of my most used packages but with fewer interactions. I currently creating a new (and hopefully better) version of scikit-criteria, This is not an easy fix, i gonna try to find the simplest workaround.

**Comment by leliel12** [comment]
Hi guys thanks to @dand-oss the version 0.2.11 works again with the new pulp version.

Please upgrade with `pip install -U pulp scikit-criteria` (the `-U` is important) 

I currently working on scikit-criteria 0.5, with an entire redesign to make more easy create multiple experiments (more like scikit-learn pipelines) please subscribe to the scikit-criteria mailing list) https://groups.google.com/forum/#!forum/scikit-criteria
